export const DATA = [
  "The quick brown fox jumps over the lazy dog.",
  "She sells seashells by the seashore.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
  "Peter Piper picked a peck of pickled peppers.",
  "A good cook could cook as much cookies as a good cook who could cook cookies.",
  "I scream, you scream, we all scream for ice cream.",
  "He thrusts his fists against the posts and still insists he sees the ghosts.",
  "Betty Botter bought some butter, but she said the butter’s bitter.",
  "She stood on the balcony, inexplicably mimicking him hiccuping and amicably welcoming him in.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "How can a clam cram in a clean cream can?",
  "I have got a date at a quarter to eight; I'll see you at the gate, so don’t be late.",
  "You know New York, you need New York, you know you need unique New York.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "Can you can a can as a canner can can a can?",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "Pad kid poured curd pulled cod.",
  "The sixth sick sheik's sixth sheep's sick.",
  "Six slippery snails slid slowly seaward.",
  "A black bug bleeds black blood, but a blue bug bleeds blue blood.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "We surely shall see the sun shine soon.",
  "I saw Susie sitting in a shoeshine shop.",
  "Four fine fresh fish for you.",
  "So, this is the sushi chef.",
  "Thin sticks, thick bricks.",
  "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.",
  "Lesser leather never weathered wetter weather better.",
  "Each Easter Eddie eats eighty Easter eggs.",
  "Gobbling gorgoyles gobbled gobbling goblins.",
  "If Stu chews shoes, should Stu choose the shoes he chews?",
  "Lesser leather never weathered wetter weather better.",
  "Which wristwatches are Swiss wristwatches?",
  "How many yaks could a yak pack pack if a yak pack could pack yaks?",
  "A tutor who tooted the flute tried to tutor two tooters to toot.",
  "The two tooters who were tooting the flute found that the toot tasted good.",
  "How many cookies could a good cook cook if a good cook could cook cookies?",
  "Mix a box of mixed biscuits with a boxed biscuit mixer.",
  "When the pitcher hit the pitch, the umpire made a bad pitch call.",
  "He threw three free throws.",
  "Nine nice night nurses nursing nicely.",
  "The great Greek grape growers grow great Greek grapes.",
  "Fred fed Ted bread and Ted fed Fred bread.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Blake's black bike's back brake bracket block broke.",
  "The blue bluebird blinks.",
  "Red lorry, yellow lorry.",
  "Tom threw Tim three thumbtacks.",
  "A snake sneaks to seek a snack.",
  "Three free throws.",
  "The sun shines on shop signs.",
  "She sees cheese.",
  "He threw three free throws.",
  "Chester cheetah chews a chunk of cheap cheddar cheese.",
  "If a black bug bleeds black blood, what color blood does a blue bug bleed?",
  "Black background, brown background.",
  "Ed had edited it.",
  "An ape hates grape cakes.",
  "I saw a kitten eating chicken in the kitchen.",
  "Give papa a cup of proper coffee in a copper coffee cup.",
  "Willie's really weary.",
  "I saw Esau kissing Kate. I saw Esau, he saw me, and she saw I saw Esau.",
  "Eddie edited it.",
  "Sheena leads, Sheila needs.",
  "Great gray goats.",
  "A box of biscuits, a batch of mixed biscuits.",
  "A box of mixed biscuits and a biscuit mixer.",
  "Silly Sally swiftly shooed seven silly sheep.",
  "Six sticky skeletons.",
  "Can you can a can as a canner can can a can?",
  "Four furious friends fought for the phone.",
  "Sheena leads, Sheila needs.",
  "The big bug bit the little beetle, but the little beetle bit the big bug back.",
  "One-one was a racehorse. Two-two was one too. One-one won one race. Two-two won one too.",
  "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "A pessimistic pest exists amid us.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "The quick brown fox jumps over the lazy dog.",
  "Betty loves the velvet vest best.",
  "Six slippery snails slid slowly seaward.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "Sheena leads, Sheila needs.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "Can you can a can as a canner can can a can?",
  "She sees cheese.",
  "How can a clam cram in a clean cream can?",
  "You know New York, you need New York, you know you need unique New York.",
  "Nine nice night nurses nursing nicely.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "The quick brown fox jumps over the lazy dog.",
  "She sells seashells by the seashore.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
  "Peter Piper picked a peck of pickled peppers.",
  "A good cook could cook as much cookies as a good cook who could cook cookies.",
  "I scream, you scream, we all scream for ice cream.",
  "He thrusts his fists against the posts and still insists he sees the ghosts.",
  "Betty Botter bought some butter, but she said the butter’s bitter.",
  "She stood on the balcony, inexplicably mimicking him hiccuping and amicably welcoming him in.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "How can a clam cram in a clean cream can?",
  "I have got a date at a quarter to eight; I'll see you at the gate, so don’t be late.",
  "You know New York, you need New York, you know you need unique New York.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "Can you can a can as a canner can can a can?",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "Pad kid poured curd pulled cod.",
  "The sixth sick sheik's sixth sheep's sick.",
  "Six slippery snails slid slowly seaward.",
  "A black bug bleeds black blood, but a blue bug bleeds blue blood.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "We surely shall see the sun shine soon.",
  "I saw Susie sitting in a shoeshine shop.",
  "Four fine fresh fish for you.",
  "So, this is the sushi chef.",
  "Thin sticks, thick bricks.",
  "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.",
  "Lesser leather never weathered wetter weather better.",
  "Each Easter Eddie eats eighty Easter eggs.",
  "Gobbling gorgoyles gobbled gobbling goblins.",
  "If Stu chews shoes, should Stu choose the shoes he chews?",
  "Lesser leather never weathered wetter weather better.",
  "Which wristwatches are Swiss wristwatches?",
  "How many yaks could a yak pack pack if a yak pack could pack yaks?",
  "A tutor who tooted the flute tried to tutor two tooters to toot.",
  "The two tooters who were tooting the flute found that the toot tasted good.",
  "How many cookies could a good cook cook if a good cook could cook cookies?",
  "Mix a box of mixed biscuits with a boxed biscuit mixer.",
  "When the pitcher hit the pitch, the umpire made a bad pitch call.",
  "He threw three free throws.",
  "Nine nice night nurses nursing nicely.",
  "The great Greek grape growers grow great Greek grapes.",
  "Fred fed Ted bread and Ted fed Fred bread.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Blake's black bike's back brake bracket block broke.",
  "The blue bluebird blinks.",
  "Red lorry, yellow lorry.",
  "Tom threw Tim three thumbtacks.",
  "A snake sneaks to seek a snack.",
  "Three free throws.",
  "The sun shines on shop signs.",
  "She sees cheese.",
  "He threw three free throws.",
  "Chester cheetah chews a chunk of cheap cheddar cheese.",
  "If a black bug bleeds black blood, what color blood does a blue bug bleed?",
  "Black background, brown background.",
  "Ed had edited it.",
  "An ape hates grape cakes.",
  "I saw a kitten eating chicken in the kitchen.",
  "Give papa a cup of proper coffee in a copper coffee cup.",
  "Willie's really weary.",
  "I saw Esau kissing Kate. I saw Esau, he saw me, and she saw I saw Esau.",
  "Eddie edited it.",
  "Sheena leads, Sheila needs.",
  "Great gray goats.",
  "A box of biscuits, a batch of mixed biscuits.",
  "A box of mixed biscuits and a biscuit mixer.",
  "Silly Sally swiftly shooed seven silly sheep.",
  "Six sticky skeletons.",
  "Can you can a can as a canner can can a can?",
  "Four furious friends fought for the phone.",
  "Sheena leads, Sheila needs.",
  "The big bug bit the little beetle, but the little beetle bit the big bug back.",
  "One-one was a racehorse. Two-two was one too. One-one won one race. Two-two won one too.",
  "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "A pessimistic pest exists amid us.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "The quick brown fox jumps over the lazy dog.",
  "Betty loves the velvet vest best.",
  "Six slippery snails slid slowly seaward.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "Sheena leads, Sheila needs.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "Can you can a can as a canner can can a can?",
  "She sees cheese.",
  "How can a clam cram in a clean cream can?",
  "You know New York, you need New York, you know you need unique New York.",
  "Nine nice night nurses nursing nicely.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "The quick brown fox jumps over the lazy dog.",
  "She sells seashells by the seashore.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
  "Peter Piper picked a peck of pickled peppers.",
  "A good cook could cook as much cookies as a good cook who could cook cookies.",
  "I scream, you scream, we all scream for ice cream.",
  "He thrusts his fists against the posts and still insists he sees the ghosts.",
  "Betty Botter bought some butter, but she said the butter’s bitter.",
  "She stood on the balcony, inexplicably mimicking him hiccuping and amicably welcoming him in.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "How can a clam cram in a clean cream can?",
  "I have got a date at a quarter to eight; I'll see you at the gate, so don’t be late.",
  "You know New York, you need New York, you know you need unique New York.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "Can you can a can as a canner can can a can?",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "Pad kid poured curd pulled cod.",
  "The sixth sick sheik's sixth sheep's sick.",
  "Six slippery snails slid slowly seaward.",
  "A black bug bleeds black blood, but a blue bug bleeds blue blood.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "We surely shall see the sun shine soon.",
  "I saw Susie sitting in a shoeshine shop.",
  "Four fine fresh fish for you.",
  "So, this is the sushi chef.",
  "Thin sticks, thick bricks.",
  "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.",
  "Lesser leather never weathered wetter weather better.",
  "Each Easter Eddie eats eighty Easter eggs.",
  "Gobbling gorgoyles gobbled gobbling goblins.",
  "If Stu chews shoes, should Stu choose the shoes he chews?",
  "Lesser leather never weathered wetter weather better.",
  "Which wristwatches are Swiss wristwatches?",
  "How many yaks could a yak pack pack if a yak pack could pack yaks?",
  "A tutor who tooted the flute tried to tutor two tooters to toot.",
  "The two tooters who were tooting the flute found that the toot tasted good.",
  "How many cookies could a good cook cook if a good cook could cook cookies?",
  "Mix a box of mixed biscuits with a boxed biscuit mixer.",
  "When the pitcher hit the pitch, the umpire made a bad pitch call.",
  "He threw three free throws.",
  "Nine nice night nurses nursing nicely.",
  "The great Greek grape growers grow great Greek grapes.",
  "Fred fed Ted bread and Ted fed Fred bread.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Blake's black bike's back brake bracket block broke.",
  "The blue bluebird blinks.",
  "Red lorry, yellow lorry.",
  "Tom threw Tim three thumbtacks.",
  "A snake sneaks to seek a snack.",
  "Three free throws.",
  "The sun shines on shop signs.",
  "She sees cheese.",
  "He threw three free throws.",
  "Chester cheetah chews a chunk of cheap cheddar cheese.",
  "If a black bug bleeds black blood, what color blood does a blue bug bleed?",
  "Black background, brown background.",
  "Ed had edited it.",
  "An ape hates grape cakes.",
  "I saw a kitten eating chicken in the kitchen.",
  "Give papa a cup of proper coffee in a copper coffee cup.",
  "Willie's really weary.",
  "I saw Esau kissing Kate. I saw Esau, he saw me, and she saw I saw Esau.",
  "Eddie edited it.",
  "Sheena leads, Sheila needs.",
  "Great gray goats.",
  "A box of biscuits, a batch of mixed biscuits.",
  "A box of mixed biscuits and a biscuit mixer.",
  "Silly Sally swiftly shooed seven silly sheep.",
  "Six sticky skeletons.",
  "Can you can a can as a canner can can a can?",
  "Four furious friends fought for the phone.",
  "Sheena leads, Sheila needs.",
  "The big bug bit the little beetle, but the little beetle bit the big bug back.",
  "One-one was a racehorse. Two-two was one too. One-one won one race. Two-two won one too.",
  "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "A pessimistic pest exists amid us.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "The quick brown fox jumps over the lazy dog.",
  "Betty loves the velvet vest best.",
  "Six slippery snails slid slowly seaward.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "Sheena leads, Sheila needs.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "Can you can a can as a canner can can a can?",
  "She sees cheese.",
  "How can a clam cram in a clean cream can?",
  "You know New York, you need New York, you know you need unique New York.",
  "Nine nice night nurses nursing nicely.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "The quick brown fox jumps over the lazy dog.",
  "She sells seashells by the seashore.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
  "Peter Piper picked a peck of pickled peppers.",
  "A good cook could cook as much cookies as a good cook who could cook cookies.",
  "I scream, you scream, we all scream for ice cream.",
  "He thrusts his fists against the posts and still insists he sees the ghosts.",
  "Betty Botter bought some butter, but she said the butter’s bitter.",
  "She stood on the balcony, inexplicably mimicking him hiccuping and amicably welcoming him in.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "How can a clam cram in a clean cream can?",
  "I have got a date at a quarter to eight; I'll see you at the gate, so don’t be late.",
  "You know New York, you need New York, you know you need unique New York.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "Can you can a can as a canner can can a can?",
  "Six sick hicks nick six slick bricks with picks and sticks.",
  "Pad kid poured curd pulled cod.",
  "The sixth sick sheik's sixth sheep's sick.",
  "Six slippery snails slid slowly seaward.",
  "A black bug bleeds black blood, but a blue bug bleeds blue blood.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "We surely shall see the sun shine soon.",
  "I saw Susie sitting in a shoeshine shop.",
  "Four fine fresh fish for you.",
  "So, this is the sushi chef.",
  "Thin sticks, thick bricks.",
  "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.",
  "Lesser leather never weathered wetter weather better.",
  "Each Easter Eddie eats eighty Easter eggs.",
  "Gobbling gorgoyles gobbled gobbling goblins.",
  "If Stu chews shoes, should Stu choose the shoes he chews?",
  "Lesser leather never weathered wetter weather better.",
  "Which wristwatches are Swiss wristwatches?",
  "How many yaks could a yak pack pack if a yak pack could pack yaks?",
  "A tutor who tooted the flute tried to tutor two tooters to toot.",
  "The two tooters who were tooting the flute found that the toot tasted good.",
  "How many cookies could a good cook cook if a good cook could cook cookies?",
  "Mix a box of mixed biscuits with a boxed biscuit mixer.",
  "When the pitcher hit the pitch, the umpire made a bad pitch call.",
  "He threw three free throws.",
  "Nine nice night nurses nursing nicely.",
  "The great Greek grape growers grow great Greek grapes.",
  "Fred fed Ted bread and Ted fed Fred bread.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Blake's black bike's back brake bracket block broke.",
  "The blue bluebird blinks.",
  "Red lorry, yellow lorry.",
  "Tom threw Tim three thumbtacks.",
  "A snake sneaks to seek a snack.",
  "Three free throws.",
  "The sun shines on shop signs.",
  "She sees cheese.",
  "He threw three free throws.",
  "Chester cheetah chews a chunk of cheap cheddar cheese.",
  "If a black bug bleeds black blood, what color blood does a blue bug bleed?",
  "Black background, brown background.",
  "Ed had edited it.",
  "An ape hates grape cakes.",
  "I saw a kitten eating chicken in the kitchen.",
  "Give papa a cup of proper coffee in a copper coffee cup.",
  "Willie's really weary.",
  "I saw Esau kissing Kate. I saw Esau, he saw me, and she saw I saw Esau.",
  "Eddie edited it.",
  "Sheena leads, Sheila needs.",
  "Great gray goats.",
  "A box of biscuits, a batch of mixed biscuits.",
  "A box of mixed biscuits and a biscuit mixer.",
  "Silly Sally swiftly shooed seven silly sheep.",
  "Six sticky skeletons.",
  "Can you can a can as a canner can can a can?",
  "Four furious friends fought for the phone.",
  "Sheena leads, Sheila needs.",
  "The big bug bit the little beetle, but the little beetle bit the big bug back.",
  "One-one was a racehorse. Two-two was one too. One-one won one race. Two-two won one too.",
  "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "A pessimistic pest exists amid us.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "The quick brown fox jumps over the lazy dog.",
  "Betty loves the velvet vest best.",
  "Six slippery snails slid slowly seaward.",
  "Fred fed Ted bread, and Ted fed Fred bread.",
  "Sheena leads, Sheila needs.",
  "The big black bug bit the big black bear, but the big black bear bit the big black bug back.",
  "Can you can a can as a canner can can a can?",
  "She sees cheese.",
  "How can a clam cram in a clean cream can?",
  "You know New York, you need New York, you know you need unique New York.",
  "Nine nice night nurses nursing nicely.",
  "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.",
  "Six sick hicks nick six slick bricks with picks and sticks.",
];
